### PR TITLE
Add requirements files. Get readthedocs working.

### PR DESCRIPTION
**Pull request by ixjlyons**
I think this should *just work* as long as readthedocs is pointed to `requirements-dev.txt`. Setting that in the admin settings is the easiest thing to do, but we could also/instead use a `.readthedocs.yml` file.

### CODE REVIEW

**Comment by ixjlyons** [comment]
Not sure if we actually care to maintain the different `extras_require` options but I also forgot to add `sphinx_gallery` before.

**Comment by sixpearls** [comment]
I'm getting this traceback. I'll investigate, but now I feel concerned I'm slowing this down. Is there a way we can both have access to the RTD console for the same project?

```
Running Sphinx v1.8.5

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/ndsplines/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ndsplines/envs/latest/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ndsplines/checkouts/latest/docs/conf.py", line 16, in <module>
    import ndsplines
  File "/home/docs/checkouts/readthedocs.org/user_builds/ndsplines/checkouts/latest/ndsplines/__init__.py", line 1, in <module>
    from .ndsplines import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/ndsplines/checkouts/latest/ndsplines/ndsplines.py", line 4, in <module>
    from ndsplines._bspl import evaluate_spline
ModuleNotFoundError: No module named 'ndsplines._bspl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/ndsplines/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ndsplines/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 201, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ndsplines/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 203, in read
    namespace = eval_config_file(filename, tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ndsplines/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 380, in eval_config_file
    raise ConfigError(msg % traceback.format_exc())
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/ndsplines/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ndsplines/envs/latest/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ndsplines/checkouts/latest/docs/conf.py", line 16, in <module>
    import ndsplines
  File "/home/docs/checkouts/readthedocs.org/user_builds/ndsplines/checkouts/latest/ndsplines/__init__.py", line 1, in <module>
    from .ndsplines import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/ndsplines/checkouts/latest/ndsplines/ndsplines.py", line 4, in <module>
    from ndsplines._bspl import evaluate_spline
ModuleNotFoundError: No module named 'ndsplines._bspl'


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/ndsplines/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ndsplines/envs/latest/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/ndsplines/checkouts/latest/docs/conf.py", line 16, in <module>
    import ndsplines
  File "/home/docs/checkouts/readthedocs.org/user_builds/ndsplines/checkouts/latest/ndsplines/__init__.py", line 1, in <module>
    from .ndsplines import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/ndsplines/checkouts/latest/ndsplines/ndsplines.py", line 4, in <module>
    from ndsplines._bspl import evaluate_spline
ModuleNotFoundError: No module named 'ndsplines._bspl'
```

**Comment by sixpearls** [comment]
I enabled the `install project` option, and got a few warnings (below) but it seemed to install. But when sphinx tried to build afterwards, I got the same error as above.

```
Compiling ndsplines/_bspl.pyx because it changed.
[1/1] Cythonizing ndsplines/_bspl.pyx
running install
running bdist_egg
running egg_info
creating ndsplines.egg-info
writing ndsplines.egg-info/PKG-INFO
writing dependency_links to ndsplines.egg-info/dependency_links.txt
writing requirements to ndsplines.egg-info/requires.txt
writing top-level names to ndsplines.egg-info/top_level.txt
writing manifest file 'ndsplines.egg-info/SOURCES.txt'
reading manifest file 'ndsplines.egg-info/SOURCES.txt'
writing manifest file 'ndsplines.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.7
creating build/lib.linux-x86_64-3.7/ndsplines
copying ndsplines/ndsplines.py -> build/lib.linux-x86_64-3.7/ndsplines
copying ndsplines/__init__.py -> build/lib.linux-x86_64-3.7/ndsplines
running build_ext
building 'ndsplines._bspl' extension
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/ndsplines
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Indsplines -I/home/docs/checkouts/readthedocs.org/user_builds/ndsplines/envs/latest/lib/python3.7/site-packages/numpy/core/include -I/home/docs/.pyenv/versions/3.7.1/include/python3.7m -c ndsplines/_bspl.c -o build/temp.linux-x86_64-3.7/ndsplines/_bspl.o
In file included from /home/docs/checkouts/readthedocs.org/user_builds/ndsplines/envs/latest/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
                 from /home/docs/checkouts/readthedocs.org/user_builds/ndsplines/envs/latest/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/docs/checkouts/readthedocs.org/user_builds/ndsplines/envs/latest/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from ndsplines/_bspl.c:615:
/home/docs/checkouts/readthedocs.org/user_builds/ndsplines/envs/latest/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
ndsplines/_bspl.c: In function ‘__pyx_pf_9ndsplines_5_bspl_evaluate_spline’:
ndsplines/_bspl.c:3148:21: warning: passing argument 1 of ‘_deBoor_D’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
           _deBoor_D((&(*((double const  *) ( /* dim=0 */ ((char *) (((double const  *) __pyx_v_t.data) + __pyx_t_13)) )))), __pyx_v_xval, __pyx_v_k, __pyx_v_interval, __pyx_v_nu, (&(*((double *) ( /* dim=1 */ ((char *) (((double *) ( /* dim=0 */ (__pyx_v_basis_workspace.data + __pyx_t_14 * __pyx_v_basis_workspace.strides[0]) )) + __pyx_t_15)) )))));
                     ^
In file included from ndsplines/_bspl.c:617:0:
ndsplines/_bspl.h:6:1: note: expected ‘double *’ but argument is of type ‘const double *’
 _deBoor_D(double *t, double x, int k, int ell, int m, double *result) {
 ^~~~~~~~~
gcc -pthread -shared -L/home/docs/.pyenv/versions/3.7.1/lib -L/home/docs/.pyenv/versions/3.7.1/lib build/temp.linux-x86_64-3.7/ndsplines/_bspl.o -o build/lib.linux-x86_64-3.7/ndsplines/_bspl.cpython-37m-x86_64-linux-gnu.so
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/ndsplines
copying build/lib.linux-x86_64-3.7/ndsplines/ndsplines.py -> build/bdist.linux-x86_64/egg/ndsplines
copying build/lib.linux-x86_64-3.7/ndsplines/_bspl.cpython-37m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/ndsplines
copying build/lib.linux-x86_64-3.7/ndsplines/__init__.py -> build/bdist.linux-x86_64/egg/ndsplines
byte-compiling build/bdist.linux-x86_64/egg/ndsplines/ndsplines.py to ndsplines.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/ndsplines/__init__.py to __init__.cpython-37.pyc
creating stub loader for ndsplines/_bspl.cpython-37m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/ndsplines/_bspl.py to _bspl.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying ndsplines.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ndsplines.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ndsplines.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ndsplines.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ndsplines.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
/home/docs/checkouts/readthedocs.org/user_builds/ndsplines/envs/latest/lib/python3.7/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/docs/checkouts/readthedocs.org/user_builds/ndsplines/checkouts/latest/ndsplines/_bspl.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
zip_safe flag not set; analyzing archive contents...
ndsplines.__pycache__._bspl.cpython-37: module references __file__
creating dist
creating 'dist/ndsplines-0.0.1-py3.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing ndsplines-0.0.1-py3.7-linux-x86_64.egg
creating /home/docs/checkouts/readthedocs.org/user_builds/ndsplines/envs/latest/lib/python3.7/site-packages/ndsplines-0.0.1-py3.7-linux-x86_64.egg
Extracting ndsplines-0.0.1-py3.7-linux-x86_64.egg to /home/docs/checkouts/readthedocs.org/user_builds/ndsplines/envs/latest/lib/python3.7/site-packages
Adding ndsplines 0.0.1 to easy-install.pth file

Installed /home/docs/checkouts/readthedocs.org/user_builds/ndsplines/envs/latest/lib/python3.7/site-packages/ndsplines-0.0.1-py3.7-linux-x86_64.egg
Processing dependencies for ndsplines==0.0.1
Searching for scipy==1.2.1
Best match: scipy 1.2.1
Adding scipy 1.2.1 to easy-install.pth file

Using /home/docs/checkouts/readthedocs.org/user_builds/ndsplines/envs/latest/lib/python3.7/site-packages
Searching for numpy==1.16.3
Best match: numpy 1.16.3
Adding numpy 1.16.3 to easy-install.pth file
Installing f2py script to /home/docs/checkouts/readthedocs.org/user_builds/ndsplines/envs/latest/bin
Installing f2py3 script to /home/docs/checkouts/readthedocs.org/user_builds/ndsplines/envs/latest/bin
Installing f2py3.7 script to /home/docs/checkouts/readthedocs.org/user_builds/ndsplines/envs/latest/bin

Using /home/docs/checkouts/readthedocs.org/user_builds/ndsplines/envs/latest/lib/python3.7/site-packages
Searching for Cython==0.29.7
Best match: Cython 0.29.7
Adding Cython 0.29.7 to easy-install.pth file
Installing cygdb script to /home/docs/checkouts/readthedocs.org/user_builds/ndsplines/envs/latest/bin
Installing cython script to /home/docs/checkouts/readthedocs.org/user_builds/ndsplines/envs/latest/bin
Installing cythonize script to /home/docs/checkouts/readthedocs.org/user_builds/ndsplines/envs/latest/bin

Using /home/docs/checkouts/readthedocs.org/user_builds/ndsplines/envs/latest/lib/python3.7/site-packages
Finished processing dependencies for ndsplines==0.0.1
```

**Comment by ixjlyons** [comment]
Oh sorry I should have mentioned that you'll need to enable the installation option so it'll actually compile. Strange that sphinx still fails though -- should have known it wouldn't be that easy. You can add me as a maintainer in the admin settings (ixjlyons).

**Comment by ixjlyons** [comment]
Ah, I actually can access the builds (https://readthedocs.org/projects/ndsplines/builds/) so that's enough I think for now at least. Latest error is that sphinx changed the default "master doc" from `contents.rst` to `index.rst` in version 2, so they dropped the `master_doc = 'index.rst'` line from `conf.py` when you use `sphinx>=2` during `sphinx-quickstart` (it is as though they encouraged the change for a while then enforced it with 2.0 release). I don't necessarily feel compelled to require `sphinx>=2`, so next commit should work.

**Comment by ixjlyons** [comment]
:tada: https://ndsplines.readthedocs.io/en/init-docs/index.html

**Comment by sixpearls** [comment]
Amazing, thanks!

**Pull request merged**
