### PR TITLE
Initial package setup done

### PR DESCRIPTION
**Pull request by ixjlyons**
This is still work in progress. Now that things have moved around, I'm getting this error when running the examples for some reason:

```
Traceback (most recent call last):
  File "1d-interp.py", line 39, in <module>
    NDsplienf = test_NDBspline(xx.copy())
  File "/home/kenny/src/ndsplines/ndsplines/ndsplines.py", line 136, in __call__
    self.compute_basis_coefficient_selector(x, nus)        
  File "/home/kenny/src/ndsplines/ndsplines/ndsplines.py", line 96, in compute_basis_coefficient_selector
    scipy_bspl.evaluate_spline(t, k, x[i,:], nu, extrapolate_flag, self.interval_workspace[i], self.basis_workspace[i],)
  File "ndsplines/scipy_bspl.pyx", line 97, in ndsplines.scipy_bspl.evaluate_spline
    int[::1] interval_workspace,
ValueError: Buffer dtype mismatch, expected 'int' but got 'long'
```

I see that `interval_workspace` array is explicitly initialized as `np.int_`, so I'm not sure why this would happen.

@sixpearls could you try checking out this branch and running the steps I added in the README? That'll help figure out if the package setup or my system setup is the problem. Anything obvious I'm missing?

### CODE REVIEW

**Comment by sixpearls** [comment]
It built and ran for me in my IDE and calling from the command line. And when I ran the profile script, I got really good results:

   scipy:  0.40584226631873394
ndspline:  0.6536146377511576

This is the first time I profiled in a fresh virtual environment, not sure if that's main factor.

**Comment by ixjlyons** [comment]
Ok, so it's still not 100% clear to me what the best practice is here, but according to NumPy's docs, `dtype=np.int_` in Python maps to a C `long`: https://docs.scipy.org/doc/numpy/user/basics.types.html#array-types-and-conversions-between-types

So ignoring that the examples were running for me previously and given that it's working for you now, there must be some platform-specific behavior happening. I think a good platform-agnostic way to solve this would be to change the Cython function signature:

```cython
int[::1] interval_workspace --> cnp.int_t[::1] interval_workspace
```

Alternatively, I think we could use `np.intc` or `np.int32` on the Python side, but it feels better to leave the type details to the cython code.

If that works for you (I'll push that change in a sec), I'd say the initial packaging is done and I can move on to more rearranging and docs.

**Comment by ixjlyons** [comment]
I found one place where SciPy uses [`cdef int[:]`](https://github.com/scipy/scipy/blob/bbe064031c757351688daf0c37b3e166e342efca/scipy/interpolate/_ppoly.pyx#L120) paired with [`dtype=np.intc`](https://github.com/scipy/scipy/blob/bbe064031c757351688daf0c37b3e166e342efca/scipy/interpolate/interpolate.py#L2041-L2048).

scikit-learn uses `int[:]` paired with SciPy's `csr_matrix.indices`, which actually has its dtype determined dynamically based on whether or not the array shape will fit in a 32-bit int (which I think means you'd get the "expected 'int' but got 'long'" error if you pass a huge dataset to the sklearn model that uses that function).

scikit-image has a cython "header" file that defines an `np_anyint` type to deal with this issue: https://github.com/scikit-image/scikit-image/blob/master/skimage/_shared/fused_numerics.pxd

Here's what I'm getting with `1d-profile.py`:

### `np.int_` and `long`:

```
timing external run1
   scipy:  0.2170227039987367
ndspline:  0.5525698599994939
timing external run big
   scipy:  0.09947053600080835
ndspline:  0.1644847719999234
```

### `np.int_` and `cnp.int_t`:

```
timing external run1
   scipy:  0.21762925899929542
ndspline:  0.5542779899988091
timing external run big
   scipy:  0.09930888000053528
ndspline:  0.16274683299889148
```

### `np.intc` and `int`:

```
timing external run1
   scipy:  0.222467523000887
ndspline:  0.5669853309991595
timing external run big
   scipy:  0.10046708499976376
ndspline:  0.16383783899982518
```

So I'd call that no effect. Should we just go with `np.int_` and `long`?

**Comment by sixpearls** [comment]
Sounds good. You seemed to get less variability across builds than I get run-to-run for each build on both Win10 and OSX. I'm probably just seeing noise, so we can just choose one based on aesthetics. That makes me lean toward `np.intc` and `int`, but not strongly. Did you have a preference? Did you like your first solution?

**Comment by ixjlyons** [comment]
I suspect I'm seeing low noise because I run a pretty minimal setup. The generated binaries *are* different, but looking at the generated C code, I'd be pretty surprised if there was a practical difference unless certain compilers do something strange/optimized (could be either tbh). Anyway, let's go with `np.intc` and `int`.

**Pull request merged**
